apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: resumematch
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: resumematch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: resumematch/api:local
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          command:
            - sh
            - -c
            - |
              until pg_isready -h "$POSTGRES_HOST" -p 5432 -U "$POSTGRES_USER"; do echo waiting for postgres; sleep 2; done
        - name: migrate
          image: resumematch/api:local
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          command:
            - python
            - manage.py
            - migrate
            - --noinput
      containers:
        - name: api
          image: resumematch/api:local
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 8000
          command:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10